from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(War)
admin.site.register(Guild)
admin.site.register(Card)
admin.site.register(Challenge)
admin.site.register(Donation)
admin.site.register(Player)
admin.site.register(Is_War_Match)
admin.site.register(Match)
admin.site.register(Participate)
admin.site.register(Player_Card)
admin.site.register(Player_Challenge)
admin.site.register(Player_Guild)
admin.site.register(Spell)
admin.site.register(Structure)
admin.site.register(Troop)
admin.site.register(User)
admin.site.register(Scopes)
admin.site.register(Roles)
admin.site.register(User_Scopes)
admin.site.register(Roles_Scopes)
admin.site.register(OAuth)