from django.urls import path
from .views import *

urlpatterns = [
    # path('wars/', WarView.as_view()),
    # path('wars/<int:id>', WarView.as_view()),
    path('wars/', ListCreateWarAPIView.as_view()),
    path('wars/<pk>', RetrieveUpdateDestroyWarAPIView.as_view()),
    path('guilds/', ListCreateGuildAPIView.as_view()),
    path('guilds/<pk>', RetrieveUpdateDestroyGuildAPIView.as_view()),
    path('cards/', ListCreateGuildAPIView.as_view()),
    path('cards/<pk>', RetrieveUpdateDestroyCardAPIView.as_view()),
    path('challenges/', ListCreateChallengeAPIView.as_view()),
    path('challenges/<pk>', RetrieveUpdateDestroyChallengeAPIView.as_view()),
    path('donations/', ListCreateDonationAPIView.as_view()),
    path('donations/<pk>', RetrieveUpdateDestroyDonationAPIView.as_view()),
    path('players/', ListCreatePlayerAPIView.as_view()),
    path('players/<pk>', RetrieveUpdateDestroyPlayerAPIView.as_view()),
    path('is_war_matchs/', ListCreateIs_War_MatchAPIView.as_view()),
    path('is_war_matchs/<pk>', RetrieveUpdateDestroyIs_War_MatchAPIView.as_view()),
    path('matchs/', ListCreateMatchAPIView.as_view()),
    path('matchs/<pk>', RetrieveUpdateDestroyMatchAPIView.as_view()),
    path('participates/', ListCreateParticipateAPIView.as_view()),
    path('participates/<pk>', RetrieveUpdateDestroyParticipateAPIView.as_view()),
    path('player_cards/', ListCreatePlayer_CardAPIView.as_view()),
    path('player_cards/<pk>', RetrieveUpdateDestroyPlayer_CardAPIView.as_view()),
    path('player_challenges/', ListCreatePlayer_ChallengeAPIView.as_view()),
    path('player_challenges/<pk>', RetrieveUpdateDestroyPlayer_ChallengeAPIView.as_view()),
    path('player_guilds/', ListCreatePlayer_GuildAPIView.as_view()),
    path('player_guilds/<pk>', RetrieveUpdateDestroyPlayer_GuildAPIView.as_view()),
    path('spells/', ListCreateSpellAPIView.as_view()),
    path('spells/<pk>', RetrieveUpdateDestroySpellAPIView.as_view()),
    path('structures/', ListCreateStructureAPIView.as_view()),
    path('structures/<pk>', RetrieveUpdateDestroyStructureAPIView.as_view()),
    path('troops/', ListCreateTroopAPIView.as_view()),
    path('troops/<pk>', RetrieveUpdateDestroyTroopAPIView.as_view()),
    path('challengesWinners/', challengesWinners.as_view()),
    path('playersJoinClan/<pk>', playersJoinClan.as_view())
]