# Generated by Django 4.0.5 on 2022-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_date', models.DateField()),
                ('W_duedate', models.DateField()),
            ],
        ),
    ]
