# Generated by Django 4.0.5 on 2022-06-02 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=50)),
                ('C_description', models.TextField(max_length=1000)),
                ('aviableLocation', models.CharField(max_length=50)),
                ('C_quality', models.CharField(max_length=50)),
                ('elixirCount', models.IntegerField()),
                ('initialLevel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=50)),
                ('ch_description', models.TextField(max_length=1000)),
                ('ch_dueDate', models.DateField()),
                ('ch_date', models.DateField()),
                ('ch_minLevel', models.IntegerField()),
                ('ch_cost', models.IntegerField()),
                ('ch_masPrices', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_name', models.CharField(max_length=50)),
                ('G_type', models.CharField(max_length=50)),
                ('G_description', models.TextField(max_length=1000)),
                ('region', models.CharField(max_length=50)),
                ('trophies', models.IntegerField()),
                ('needTrophies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('P_gold', models.IntegerField()),
                ('P_gems', models.IntegerField()),
                ('P_level', models.IntegerField()),
                ('P_trophies', models.IntegerField()),
                ('trophiesMax', models.IntegerField()),
                ('winCount', models.IntegerField()),
                ('prefCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_lifePoints', models.IntegerField()),
                ('T_areaDamage', models.IntegerField()),
                ('T_unitCount', models.IntegerField()),
                ('T_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ST_lifePoints', models.IntegerField()),
                ('ST_areaDamage', models.IntegerField()),
                ('ST_attackSpell', models.IntegerField()),
                ('ST_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SP_AoE', models.IntegerField()),
                ('SP_areaDamage', models.IntegerField()),
                ('SP_towerDamage', models.IntegerField()),
                ('SP_duration', models.IntegerField()),
                ('SP_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.card')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=45)),
                ('PG_G_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.guild')),
                ('PG_P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winCount', models.IntegerField()),
                ('PCH_CH_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.challenge')),
                ('PCH_P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PC_goldNeeded', models.IntegerField()),
                ('PC_cardNeeded', models.IntegerField()),
                ('PC_count', models.IntegerField()),
                ('PC_currentLevel', models.IntegerField()),
                ('PC_C_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.card')),
                ('PC_P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_G_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.guild')),
                ('P_W_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.war')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_duration', models.IntegerField()),
                ('M_date', models.DateField()),
                ('M_trophies', models.IntegerField()),
                ('P1_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player_1', to='api_rest_app.player')),
                ('P2_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player_2', to='api_rest_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Is_War_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IWM_M_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.match')),
                ('IWM_W_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.war')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donationCount', models.IntegerField()),
                ('D_C_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.card')),
                ('D_G_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.guild')),
                ('D_P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.player')),
            ],
        ),
    ]
