# Generated by Django 4.0.5 on 2022-06-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_app', '0002_card_challenge_guild_player_troop_structure_spell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OA_token', models.CharField(max_length=32)),
                ('OA_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_name', models.CharField(max_length=50)),
                ('U_email', models.CharField(max_length=50)),
                ('U_password', models.CharField(max_length=50)),
                ('U_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.roles')),
            ],
        ),
        migrations.CreateModel(
            name='User_Scopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.scopes')),
                ('U_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Roles_Scopes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.roles')),
                ('SC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest_app.scopes')),
            ],
        ),
    ]
