# Generated by Django 4.0.5 on 2022-06-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_app', '0003_oauth_roles_scopes_user_user_scopes_roles_scopes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuth',
        ),
        migrations.RemoveField(
            model_name='roles_scopes',
            name='R_ID',
        ),
        migrations.RemoveField(
            model_name='roles_scopes',
            name='SC_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='U_role',
        ),
        migrations.RemoveField(
            model_name='user_scopes',
            name='SC_ID',
        ),
        migrations.RemoveField(
            model_name='user_scopes',
            name='U_ID',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Roles_Scopes',
        ),
        migrations.DeleteModel(
            name='Scopes',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_Scopes',
        ),
    ]
