# Generated by Django 4.0.5 on 2022-06-18 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_app', '0005_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donationDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
