# Generated by Django 4.0.5 on 2022-06-19 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest_app', '0006_donation_donationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='aviableLocation',
            new_name='avaliableLocation',
        ),
    ]
